"""Writes the highlighted-email block into showcase/mock_landing_page.html (between the
BEGIN/END markers) using one corpus phishing email and the same cue-locating rules as
showcase/evidence.html. Re-run after changing the evidence items."""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "showcase" / "mock_landing_page.html"
ITEMS = ROOT / "showcase" / "evidence_items.json"
CUES = {
    "urgency": "Pressure to act now", "threats": "Threatens a consequence", "generic_greeting": "Impersonal greeting",
    "spelling_grammar": "Spelling or grammar problem", "emotional_appeal": "Emotional pull",
    "too_good_true": "Too-good-to-be-true offer", "personal_info": "Asks for sensitive details",
    "suspicious_sender": "Sender looks mismatched", "suspicious_link": "Link looks suspicious",
}
PAT = {
    "urgency": r"(act now|immediately|urgent(ly)?|today|within \d+ (hours?|days?)|as soon as possible|right away|expires?)",
    "threats": r"(suspend\w*|closed|blocked|terminat\w*|legal action|penalt\w*|lose access|will be removed|disabled|consequences?)",
    "generic_greeting": r"^(dear [^,\n]{1,40}|hello [^,\n]{1,40}|hi there|to whom it may concern)",
    "spelling_grammar": r"\b(recieve\w*|verfy|acount|pls|dont|seperate|occured|untill|wich)\b",
    "emotional_appeal": r"(congratulations|you('ve| have) been selected|urgent plea|please help|we are sorry|don'?t miss)",
    "too_good_true": r"(free|prize|reward|bonus|guaranteed|winner|lottery|gift card)",
    "personal_info": r"(password|credentials|verify your|bank (account|details)|social security|account details|confirm your (identity|details|login))",
}


def pick(items):
    best, best_n = None, -1
    for it in items[:200]:
        text = it["body"]
        n = 0
        for c in it["cues"] or []:
            if c == "suspicious_link":
                n += bool(re.search(r"https?://", text, re.I))
            elif c in PAT:
                n += bool(re.search(PAT[c], text, re.I | re.M))
        if n > best_n:
            best, best_n = it, n
    return best


def render(it):
    text, spans = it["body"], []
    for c in it["cues"] or []:
        if c == "suspicious_link":
            m = re.search(r"https?://[^\s<>\"']+", text, re.I)
        elif c in PAT:
            m = re.search(PAT[c], text, re.I | re.M)
        else:
            m = None
        if m:
            spans.append((m.start(), m.end(), c))
    out, pos = "", 0
    for s, e, c in sorted(spans):
        if s < pos:
            continue
        out += html.escape(text[pos:s]) + f'<span class="hl c-{c}" title="{html.escape(CUES[c])}">{html.escape(text[s:e])}</span>'
        pos = e
    return out + html.escape(text[pos:])


def main():
    items = json.loads(ITEMS.read_text(encoding="utf-8"))
    it = pick(items)
    body_html = render(it)
    chips = "".join(f'<span class="chip c-{c}">{html.escape(CUES.get(c, c))}</span>' for c in (it["cues"] or []))
    block = f'''<!-- BEGIN demo-reveal (generated by scripts/build_demo_reveal.py) -->
    <div class="rmail">
      <div class="rmail-h">Same kind of email, as the model saw it</div>
      <div class="rmail-from">From: {html.escape(it["sender"])}</div>
      <div class="rmail-subj">{html.escape(it["subject"])}</div>
      <div class="rmail-body">{body_html}</div>
      <div class="rmail-chips">{chips or '<span class="chip nf">No text cues: the link is the only signal</span>'}</div>
    </div>
    <!-- END demo-reveal -->
'''
    page = PAGE.read_text(encoding="utf-8")
    start, end = "<!-- BEGIN demo-reveal", "<!-- END demo-reveal -->\n"
    if start in page:
        a = page.index(start); b = page.index(end) + len(end)
        page = page[:a] + block + page[b:]
    else:
        anchor = '    <div class="cues">'
        assert page.count(anchor) == 1
        page = page.replace(anchor, block + anchor)
    css = """
  .rmail{background:var(--card); border:1px solid var(--line); border-radius:12px; padding:14px 16px; margin:12px 0; font-size:.88rem}
  .rmail-h{font-family:var(--mono); font-size:11px; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); margin-bottom:8px}
  .rmail-from{color:var(--muted); font-size:.82rem}
  .rmail-subj{font-weight:600; margin:4px 0 8px}
  .rmail-body{white-space:pre-wrap; line-height:1.6; word-break:break-word}
  .rmail-chips{display:flex; gap:6px; flex-wrap:wrap; margin-top:10px}
  .hl{color:#111; border-radius:4px; padding:1px 3px; border-bottom:2px solid; cursor:help}
  .chip{color:#111; font-size:.78rem; padding:3px 9px; border-radius:12px}
  .chip.nf{color:var(--muted); background:none; border:1px dashed var(--muted)}
  .c-urgency{background:#ffe0b2; border-color:#e65100}
  .c-threats{background:#ffcdd2; border-color:#c62828}
  .c-generic_greeting{background:#e1bee7; border-color:#6a1b9a}
  .c-spelling_grammar{background:#fff59d; border-color:#f9a825}
  .c-emotional_appeal{background:#f8bbd0; border-color:#ad1457}
  .c-too_good_true{background:#c8e6c9; border-color:#2e7d32}
  .c-personal_info{background:#b3e5fc; border-color:#0277bd}
  .c-suspicious_sender{background:#d7ccc8; border-color:#4e342e}
  .c-suspicious_link{background:#ffccbc; border-color:#bf360c}
"""
    if "/* demo-reveal css */" not in page:
        page = page.replace("</style>", "  /* demo-reveal css */" + css + "</style>", 1)
    PAGE.write_text(page, encoding="utf-8")
    print("wrote reveal with email", it["email_id"], "cues", it["cues"])


if __name__ == "__main__":
    main()
